package com.google.appinventor.components.runtime;

import com.google.appinventor.components.annotations.SimpleObject;
import com.google.appinventor.components.runtime.HandlesEventDispatching;

@SimpleObject
public interface Component {

   int ACCELEROMETER_SENSITIVITY_MODERATE = 2;
   int ACCELEROMETER_SENSITIVITY_STRONG = 3;
   int ACCELEROMETER_SENSITIVITY_WEAK = 1;
   int ALIGNMENT_CENTER = 1;
   int ALIGNMENT_NORMAL = 0;
   int ALIGNMENT_OPPOSITE = 2;
   String ASSET_DIRECTORY = "component";
   int BUTTON_SHAPE_DEFAULT = 0;
   int BUTTON_SHAPE_OVAL = 3;
   int BUTTON_SHAPE_RECT = 2;
   int BUTTON_SHAPE_ROUNDED = 1;
   int COLOR_BLACK = -16777216;
   int COLOR_BLUE = -16776961;
   int COLOR_CYAN = -16711681;
   int COLOR_DEFAULT = 0;
   int COLOR_DKGRAY = -12303292;
   int COLOR_GRAY = -7829368;
   int COLOR_GREEN = -16711936;
   int COLOR_LTGRAY = -3355444;
   int COLOR_MAGENTA = -65281;
   int COLOR_NONE = 16777215;
   int COLOR_ORANGE = -14336;
   int COLOR_PINK = -20561;
   int COLOR_RED = -65536;
   int COLOR_WHITE = -1;
   int COLOR_YELLOW = -256;
   String DEFAULT_VALUE_COLOR_BLACK = "&HFF000000";
   String DEFAULT_VALUE_COLOR_BLUE = "&HFF0000FF";
   String DEFAULT_VALUE_COLOR_CYAN = "&HFF00FFFF";
   String DEFAULT_VALUE_COLOR_DEFAULT = "&H00000000";
   String DEFAULT_VALUE_COLOR_DKGRAY = "&HFF444444";
   String DEFAULT_VALUE_COLOR_GRAY = "&HFF888888";
   String DEFAULT_VALUE_COLOR_GREEN = "&HFF00FF00";
   String DEFAULT_VALUE_COLOR_LTGRAY = "&HFFCCCCCC";
   String DEFAULT_VALUE_COLOR_MAGENTA = "&HFFFF00FF";
   String DEFAULT_VALUE_COLOR_NONE = "&H00FFFFFF";
   String DEFAULT_VALUE_COLOR_ORANGE = "&HFFFFC800";
   String DEFAULT_VALUE_COLOR_PINK = "&HFFFFAFAF";
   String DEFAULT_VALUE_COLOR_RED = "&HFFFF0000";
   String DEFAULT_VALUE_COLOR_WHITE = "&HFFFFFFFF";
   String DEFAULT_VALUE_COLOR_YELLOW = "&HFFFFFF00";
   int DIRECTION_EAST = 3;
   int DIRECTION_MAX = 4;
   int DIRECTION_MIN = -4;
   int DIRECTION_NONE = 0;
   int DIRECTION_NORTH = 1;
   int DIRECTION_NORTHEAST = 2;
   int DIRECTION_NORTHWEST = -4;
   int DIRECTION_SOUTH = -1;
   int DIRECTION_SOUTHEAST = 4;
   int DIRECTION_SOUTHWEST = -2;
   int DIRECTION_WEST = -3;
   float FONT_DEFAULT_SIZE = 14.0F;
   int LAYOUT_ORIENTATION_HORIZONTAL = 0;
   int LAYOUT_ORIENTATION_VERTICAL = 1;
   int LENGTH_FILL_PARENT = -2;
   int LENGTH_PREFERRED = -1;
   int LENGTH_UNKNOWN = -3;
   float SLIDER_MAX_VALUE = 50.0F;
   float SLIDER_MIN_VALUE = 10.0F;
   float SLIDER_THUMB_VALUE = 30.0F;
   int TOAST_LENGTH_LONG = 1;
   int TOAST_LENGTH_SHORT = 0;
   int TYPEFACE_DEFAULT = 0;
   int TYPEFACE_MONOSPACE = 3;
   int TYPEFACE_SANSSERIF = 1;
   int TYPEFACE_SERIF = 2;


   HandlesEventDispatching getDispatchDelegate();
}
