package org.acra;


public enum ReportField {

   // $FF: synthetic field
   private static final ReportField[] $VALUES = new ReportField[]{REPORT_ID, APP_VERSION_CODE, APP_VERSION_NAME, PACKAGE_NAME, FILE_PATH, PHONE_MODEL, ANDROID_VERSION, BUILD, BRAND, PRODUCT, TOTAL_MEM_SIZE, AVAILABLE_MEM_SIZE, CUSTOM_DATA, STACK_TRACE, INITIAL_CONFIGURATION, CRASH_CONFIGURATION, DISPLAY, USER_COMMENT, USER_APP_START_DATE, USER_CRASH_DATE, DUMPSYS_MEMINFO, DROPBOX, LOGCAT, EVENTSLOG, RADIOLOG, IS_SILENT, DEVICE_ID, INSTALLATION_ID, USER_EMAIL, DEVICE_FEATURES, ENVIRONMENT, SETTINGS_SYSTEM, SETTINGS_SECURE, SHARED_PREFERENCES, APPLICATION_LOG, MEDIA_CODEC_LIST, THREAD_DETAILS};
   ANDROID_VERSION,
   APPLICATION_LOG,
   APP_VERSION_CODE,
   APP_VERSION_NAME,
   AVAILABLE_MEM_SIZE,
   BRAND,
   BUILD,
   CRASH_CONFIGURATION,
   CUSTOM_DATA,
   DEVICE_FEATURES,
   DEVICE_ID,
   DISPLAY,
   DROPBOX,
   DUMPSYS_MEMINFO,
   ENVIRONMENT,
   EVENTSLOG,
   FILE_PATH,
   INITIAL_CONFIGURATION,
   INSTALLATION_ID,
   IS_SILENT,
   LOGCAT,
   MEDIA_CODEC_LIST,
   PACKAGE_NAME,
   PHONE_MODEL,
   PRODUCT,
   RADIOLOG,
   REPORT_ID,
   SETTINGS_SECURE,
   SETTINGS_SYSTEM,
   SHARED_PREFERENCES,
   STACK_TRACE,
   THREAD_DETAILS,
   TOTAL_MEM_SIZE,
   USER_APP_START_DATE,
   USER_COMMENT,
   USER_CRASH_DATE,
   USER_EMAIL;


}
